- name: install nginx
  apt:
    name: nginx
    state: present
- name: rm /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: stop nginx
  service:
    name: nginx
    state: stopped